# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:

- job: Windows

  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
        checkLatest: 'true'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm run lint
      displayName: 'npm lint'

    - script: |
        npm run test
      displayName: 'npm test'
